### ISSUE TITLE
:hidden strategy broken with new version of Gretel

### ISSUE THREAD

**Issue by dfriquet** [lassebunk/gretel-trails#2]
Hello there,

Both Gretel and Gretel-Trails are great pieces of Ruby, but it seems that a [commit in Gretel](https://github.com/lassebunk/gretel/commit/8e8b8abf62af3de85d65425c55ee0b740bb8b8a3) broke the :hidden strategy in Gretel-Trails.

``` shell
$ bundle exec rails s
.../gems/activesupport-3.2.16/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method `breadcrumb_link_to' for class `Gretel::Renderer' (NameError)
    from .../gems/activesupport-3.2.16/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
    from .../gems/gretel-trails-0.0.5/lib/gretel/trails/strategies/hidden_strategy.rb:65:in `block in <top (required)>'
    from .../gems/gretel-trails-0.0.5/lib/gretel/trails/strategies/hidden_strategy.rb:47:in `class_eval'
    from.../gems/2.0.0/gems/gretel-trails-0.0.5/lib/gretel/trails/strategies/hidden_strategy.rb:47:in `<top (required)>'
    ...
```

``` shell
$ bundle list | grep -E '\* (gretel|rails)'
  * gretel (3.0.8)
  * gretel-trails (0.0.5)
  * rails (3.2.16)
```

Before working on a patch, I'd like to know if it's worth, as this project hasn't evolved for almost a year.
In other words, is Gretel-Trails still the gem you'd use for multiple-path breadcrumbs?

Thanks a lot,
David.

**Comment by pupeno** [comment]
@dfriquet I just run into this issue. Unless there's another gem that does this, I personally would like to have this fixed.

**Comment by dfriquet** [comment]
My current workaround: fixing Gretel version in my Gemfile => `gem 'gretel', '3.0.5'`

Later versions break compatibility (despite the little version bump) while bringing too few improvements.

**Comment by pupeno** [comment]
I forked the repo and created a fix for this issue. I'm not sure if I'll encounter other issues too.

**Comment by ngelx** [comment]
+1. In addition, downgrading the gretel version did not work for my on rails 4.1

NoMethodError - undefined method `engines' for Rails::Engine::Railties:Class:
  gretel (3.0.5) lib/gretel.rb:19:in`breadcrumb_paths'
  gretel (3.0.5) lib/gretel/crumbs.rb:54:in `breadcrumb_files'
  gretel (3.0.5) lib/gretel/crumbs.rb:26:in`load_breadcrumbs'
  gretel (3.0.5) lib/gretel/crumbs.rb:36:in `reload_if_needed'
  gretel (3.0.5) lib/gretel/renderer.rb:125:in`links'
  gretel (3.0.5) lib/gretel/renderer.rb:97:in `links_for_render'
  gretel (3.0.5) lib/gretel/renderer.rb:34:in`render'
  gretel (3.0.5) lib/gretel/view_helpers.rb:55:in `breadcrumbs'
